#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
queue="$root/wiki/ingest-queue.md"
tmp="$(mktemp)"

cat > "$tmp" <<'HEADER'
# Wiki Ingest Queue

> Auto-generated by `./scripts/update-ingest-queue.sh`.
> Review these candidates during ingest. Do not edit generated items manually; update the source workspace document instead.

## Pending Candidates

HEADER

count=0

while IFS= read -r file; do
  rel="${file#"$root/"}"
  in_section=0
  while IFS= read -r line; do
    case "$line" in
      "## Wiki Promotion Candidates")
        in_section=1
        continue
        ;;
      "## "*)
        in_section=0
        ;;
    esac

    if [ "$in_section" -eq 1 ]; then
      case "$line" in
        "- [ ] "*)
          candidate="${line#- [ ] }"
          count=$((count + 1))
          printf -- '- [ ] `%s` — %s\n' "$rel" "$candidate" >> "$tmp"
          ;;
      esac
    fi
  done < "$file"
done < <(find "$root/workspaces" -type f -name '*.md' | sort)

if [ "$count" -eq 0 ]; then
  printf 'No pending ingest candidates.\n' >> "$tmp"
fi

cat >> "$tmp" <<'FOOTER'

## How To Resolve

For each pending candidate:

1. Decide whether the conclusion is stable and reusable.
2. Add or update the appropriate page under `wiki/`.
3. Update `wiki/index.md`.
4. Append `wiki/log.md`.
5. Check off the source item under `## Wiki Promotion Candidates`.
6. Run `./scripts/update-ingest-queue.sh`.
7. Run `./scripts/lint-scaffold.sh`.
FOOTER

mv "$tmp" "$queue"

printf 'Updated wiki/ingest-queue.md with %s pending candidate(s).\n' "$count"
